'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { clearAuth,getStoredUser } from '@/lib/auth';
const next:Record<string,string[]>={PACKED:['READY_FOR_PICKUP'],READY_FOR_PICKUP:['SHIPPED'],SHIPPED:['IN_TRANSIT','OUT_FOR_DELIVERY'],IN_TRANSIT:['OUT_FOR_DELIVERY'],OUT_FOR_DELIVERY:['DELIVERED','DELIVERY_FAILED'],DELIVERY_FAILED:['OUT_FOR_DELIVERY']};
export default function DeliveryDashboard(){
 const r=useRouter();const [orders,setOrders]=useState<any[]>([]);const [msg,setMsg]=useState('');const u=getStoredUser();async function load(){setOrders((await api.get('/delivery/orders')).data)}
 useEffect(()=>{const me=getStoredUser();if(!me||me.role!=='DELIVERY_AGENT'){r.replace('/login');return}load()},[r]);
 async function update(id:string,status:string){let failureReason:string|undefined;let codCollected:number|undefined;if(status==='DELIVERY_FAILED'){failureReason=prompt('Failure reason')||undefined;if(!failureReason)return}if(status==='DELIVERED'){const val=prompt('COD collected amount (leave blank for non-COD)');if(val)codCollected=Number(val)}try{await api.patch(`/delivery/orders/${id}/status`,{status,failureReason,codCollected,note:`Updated by delivery agent to ${status}`});setMsg(`Order moved to ${status}.`);await load()}catch(e:any){setMsg(e?.response?.data?.message||'Update failed.')}}
 return <main className="min-h-screen bg-[#f4f5f7] text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div><p className="font-black">Neuro Delivery</p><p className="text-xs text-slate-500">{u?.name}</p></div><button onClick={()=>{clearAuth();r.push('/login')}} className="rounded-xl border px-4 py-2 text-sm font-bold">Sign out</button></div></header><div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-4xl font-black">My deliveries</h1><p className="mt-2 text-slate-500">Assigned orders, customer location and delivery actions.</p>{msg&&<p className="mt-5 rounded-2xl border bg-white p-4 text-sm font-semibold">{msg}</p>}<section className="mt-6 space-y-4">{orders.map(o=><div key={o.id} className="rounded-3xl border bg-white p-6"><div className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-950 px-3 py-1 text-xs font-bold text-white">{o.status}</span>{o.paymentMode==='COD'&&<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">COD BDT {o.total}</span>}</div><p className="mt-4 text-xl font-black">{o.orderNumber}</p><p className="mt-1 font-bold">{o.customerName} · {o.phone}</p><p className="mt-3 text-sm">{o.addressLine}</p><p className="text-sm text-slate-500">{[o.area,o.district,o.division].filter(Boolean).join(', ')} {o.landmark?`· Landmark: ${o.landmark}`:''}</p>{o.trackingNumber&&<p className="mt-3 text-xs font-bold text-slate-500">Tracking: {o.trackingNumber}</p>}</div><div className="flex flex-wrap items-start gap-2 lg:max-w-64">{(next[o.status]||[]).map(s=><button key={s} onClick={()=>update(o.id,s)} className={`rounded-xl px-4 py-3 text-xs font-bold ${s==='DELIVERY_FAILED'?'border border-red-200 text-red-600':'bg-slate-950 text-white'}`}>{s.replaceAll('_',' ')}</button>)}</div></div></div>)}{!orders.length&&<div className="rounded-3xl border border-dashed p-12 text-center text-slate-500">No deliveries assigned.</div>}</section></div></main>
}
