'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ImagePlus, Loader2, Play, Plus, Save, Trash2, UploadCloud } from 'lucide-react';
import AdminShell from '@/components/admin-shell';
import { api } from '@/lib/api';
import { getStoredUser } from '@/lib/auth';

const emptyProduct={name:'',nameBn:'',categoryId:'',brandId:'',shortDescription:'',shortDescriptionBn:'',description:'',descriptionBn:'',primaryImageUrl:'',featured:false,media:[] as any[]};

export default function CatalogAdmin(){
  const router=useRouter();
  const [categories,setCategories]=useState<any[]>([]),[brands,setBrands]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]);
  const [message,setMessage]=useState(''),[editing,setEditing]=useState<any|null>(null),[search,setSearch]=useState(''),[product,setProduct]=useState<any>(emptyProduct);
  const [variant,setVariant]=useState({productId:'',sku:'',variantCode:'',attributesText:'Color=Black,Size=M',price:'',salePrice:'',costPrice:'',openingStock:'0',imageUrl:''});
  const [category,setCategory]=useState({name:'',nameBn:'',barcodePrefix:''});const [brand,setBrand]=useState('');const [uploading,setUploading]=useState(false);const [mediaUrl,setMediaUrl]=useState('');const [mediaType,setMediaType]=useState<'image'|'video'>('image');

  async function load(){const [c,b,p]=await Promise.all([api.get('/catalog/categories'),api.get('/catalog/brands'),api.get('/catalog/products')]);setCategories(c.data||[]);setBrands(b.data||[]);setProducts(p.data||[])}
  useEffect(()=>{const u=getStoredUser();if(!u||!['SUPER_ADMIN','ADMIN','CATALOG_MANAGER'].includes(String(u.role).toUpperCase())){router.replace('/admin?denied=1');return}load()},[router]);
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.nameBn||''} ${p.category?.name||''} ${p.category?.nameBn||''} ${p.brand?.name||''}`.toLowerCase().includes(search.toLowerCase())),[products,search]);
  const attrs=(t:string)=>Object.fromEntries(t.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [k,...v]=x.split('=');return[k.trim(),v.join('=').trim()]}).filter(([k,v])=>k&&v));

  function setField(key:string,value:any){setProduct((p:any)=>({...p,[key]:value}))}
  function addMedia(media:any){setProduct((p:any)=>({...p,media:[...(Array.isArray(p.media)?p.media:[]),media],primaryImageUrl:p.primaryImageUrl||(media.type==='image'?media.url:'')}))}
  function removeMedia(index:number){setProduct((p:any)=>{const media=[...(p.media||[])];media.splice(index,1);const firstImage=media.find((m:any)=>m.type==='image')?.url||'';return{...p,media,primaryImageUrl:p.primaryImageUrl&&media.some((m:any)=>m.url===p.primaryImageUrl)?p.primaryImageUrl:firstImage}})}

  async function upload(file:File){setUploading(true);setMessage('');try{const form=new FormData();form.append('file',file);const r=await api.post('/catalog/media/upload',form);addMedia(r.data);setMessage('Media uploaded.')}catch(e:any){setMessage(e?.response?.data?.message||'Upload failed.')}finally{setUploading(false)}}
  function addUrl(){const url=mediaUrl.trim();if(!url)return;addMedia({type:mediaType,url});setMediaUrl('')}

  async function saveProduct(e:FormEvent){e.preventDefault();try{const body={...product,brandId:product.brandId||undefined,status:editing?.status||'DRAFT'};if(editing)await api.patch(`/catalog/products/${editing.id}`,body);else await api.post('/catalog/products',body);setProduct(emptyProduct);setEditing(null);setMessage(editing?'Product updated.':'Product created.');await load()}catch(e:any){setMessage(e?.response?.data?.message||'Product save failed.')}}
  function beginEdit(p:any){setEditing(p);setProduct({name:p.name||'',nameBn:p.nameBn||'',categoryId:p.categoryId||'',brandId:p.brandId||'',shortDescription:p.shortDescription||'',shortDescriptionBn:p.shortDescriptionBn||'',description:p.description||'',descriptionBn:p.descriptionBn||'',primaryImageUrl:p.primaryImageUrl||'',featured:!!p.featured,media:Array.isArray(p.media)?p.media:[]});window.scrollTo({top:0,behavior:'smooth'})}
  async function createCategory(e:FormEvent){e.preventDefault();try{await api.post('/catalog/categories',category);setCategory({name:'',nameBn:'',barcodePrefix:''});setMessage('Category created.');await load()}catch(e:any){setMessage(e?.response?.data?.message||'Category failed.')}}
  async function createBrand(e:FormEvent){e.preventDefault();try{await api.post('/catalog/brands',{name:brand});setBrand('');setMessage('Brand created.');await load()}catch(e:any){setMessage(e?.response?.data?.message||'Brand failed.')}}
  async function createVariant(e:FormEvent){e.preventDefault();try{await api.post('/catalog/variants',{productId:variant.productId,sku:variant.sku,variantCode:variant.variantCode,attributes:attrs(variant.attributesText),price:Number(variant.price),salePrice:variant.salePrice?Number(variant.salePrice):undefined,costPrice:variant.costPrice?Number(variant.costPrice):undefined,openingStock:Number(variant.openingStock||0),imageUrl:variant.imageUrl||undefined});setVariant({productId:'',sku:'',variantCode:'',attributesText:'Color=Black,Size=M',price:'',salePrice:'',costPrice:'',openingStock:'0',imageUrl:''});setMessage('Variant created.');await load()}catch(e:any){setMessage(e?.response?.data?.message||'Variant failed.')}}
  async function activate(id:string,status:string){try{await api.patch(`/catalog/products/${id}/status?status=${status}`);setMessage(`Product ${status.toLowerCase()}.`);await load()}catch(e:any){setMessage(e?.response?.data?.message||'Status update failed.')}}

  return <AdminShell>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Catalog management</p><h1 className="mt-2 text-4xl font-black tracking-tight text-slate-900">Products, Bangla content & media</h1><p className="mt-2 text-slate-500">Manage bilingual product data, multiple images/videos, variants, prices and publishing.</p></div><input className="rounded-xl border border-slate-200 bg-white px-4 py-3" placeholder="Search catalog..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
    {message&&<div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm font-semibold text-blue-800">{message}</div>}

    <section className="mt-6 grid gap-5 xl:grid-cols-[1.5fr_.8fr]">
      <form onSubmit={saveProduct} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex justify-between gap-4"><div><h2 className="text-xl font-black">{editing?'Edit product':'New product'}</h2><p className="text-sm text-slate-500">English and বাংলা content are saved together.</p></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setProduct(emptyProduct)}} className="text-sm font-bold text-blue-600">Cancel edit</button>}</div>
        <div className="mt-5 grid gap-4 lg:grid-cols-2">
          <div className="space-y-3"><p className="text-xs font-black uppercase tracking-wider text-slate-400">English</p><input className="w-full rounded-xl border p-3" placeholder="Product name" required value={product.name} onChange={e=>setField('name',e.target.value)}/><input className="w-full rounded-xl border p-3" placeholder="Short description" value={product.shortDescription} onChange={e=>setField('shortDescription',e.target.value)}/><textarea className="min-h-28 w-full rounded-xl border p-3" placeholder="Full description" value={product.description} onChange={e=>setField('description',e.target.value)}/></div>
          <div className="space-y-3"><p className="text-xs font-black uppercase tracking-wider text-slate-400">বাংলা</p><input className="w-full rounded-xl border p-3" placeholder="পণ্যের নাম" value={product.nameBn} onChange={e=>setField('nameBn',e.target.value)}/><input className="w-full rounded-xl border p-3" placeholder="সংক্ষিপ্ত বিবরণ" value={product.shortDescriptionBn} onChange={e=>setField('shortDescriptionBn',e.target.value)}/><textarea className="min-h-28 w-full rounded-xl border p-3" placeholder="বিস্তারিত বিবরণ" value={product.descriptionBn} onChange={e=>setField('descriptionBn',e.target.value)}/></div>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2"><select className="rounded-xl border p-3" required value={product.categoryId} onChange={e=>setField('categoryId',e.target.value)}><option value="">Category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}{x.nameBn?` / ${x.nameBn}`:''}</option>)}</select><select className="rounded-xl border p-3" value={product.brandId} onChange={e=>setField('brandId',e.target.value)}><option value="">No brand</option>{brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>

        <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="font-black">Product images & videos</p><p className="text-xs text-slate-500">JPG/PNG/WEBP/GIF/MP4/WEBM/MOV, max 25 MB per file.</p></div><ImagePlus className="text-blue-600"/></div>
          <div className="mt-4 flex flex-wrap gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white"><UploadCloud size={16}/>{uploading?'Uploading...':'Upload media'}<input type="file" accept="image/*,video/mp4,video/webm,video/quicktime" className="hidden" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label><select value={mediaType} onChange={e=>setMediaType(e.target.value as any)} className="rounded-xl border bg-white px-3 text-sm font-bold"><option value="image">Image URL</option><option value="video">Video URL</option></select><input value={mediaUrl} onChange={e=>setMediaUrl(e.target.value)} placeholder="https://..." className="min-w-56 flex-1 rounded-xl border bg-white px-3 py-2.5 text-sm"/><button type="button" onClick={addUrl} className="rounded-xl border bg-white px-4 text-sm font-black"><Plus size={16}/></button></div>
          <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{(product.media||[]).map((m:any,index:number)=><div key={`${m.url}-${index}`} className="relative overflow-hidden rounded-xl border bg-white">{m.type==='video'?<div className="grid aspect-square place-items-center bg-slate-900 text-white"><Play/></div>:<img src={m.url} alt="" className="aspect-square w-full object-cover"/>}<button type="button" onClick={()=>removeMedia(index)} className="absolute right-1 top-1 grid h-7 w-7 place-items-center rounded-full bg-white/90 text-rose-600 shadow"><Trash2 size={13}/></button><p className="truncate p-2 text-[10px] text-slate-500">{m.type}</p></div>)}</div>
        </div>
        <label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={product.featured} onChange={e=>setField('featured',e.target.checked)}/> Featured product</label>
        <button className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#f36b21] px-5 py-3 font-black text-white"><Save size={16}/>{editing?'Save changes':'Create product'}</button>
      </form>

      <div className="space-y-5"><form onSubmit={createCategory} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-black">Quick category</h2><div className="mt-3 grid gap-2"><input className="rounded-xl border p-3" placeholder="English name" required value={category.name} onChange={e=>setCategory({...category,name:e.target.value})}/><input className="rounded-xl border p-3" placeholder="বাংলা নাম" value={category.nameBn} onChange={e=>setCategory({...category,nameBn:e.target.value})}/><input className="rounded-xl border p-3" placeholder="2 digit barcode prefix" maxLength={2} required value={category.barcodePrefix} onChange={e=>setCategory({...category,barcodePrefix:e.target.value})}/></div><button className="mt-3 rounded-xl border px-4 py-2 text-sm font-bold">Add category</button></form><form onSubmit={createBrand} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-black">Quick brand</h2><input className="mt-3 w-full rounded-xl border p-3" placeholder="Brand name" required value={brand} onChange={e=>setBrand(e.target.value)}/><button className="mt-3 rounded-xl border px-4 py-2 text-sm font-bold">Add brand</button></form></div>
    </section>

    <form onSubmit={createVariant} className="mt-5 rounded-[1.5rem] border border-blue-100 bg-blue-50 p-6"><h2 className="text-xl font-black text-[#123a78]">Add sellable variant</h2><p className="mt-1 text-sm text-slate-500">SKU + barcode + price + opening inventory.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><select className="rounded-xl border bg-white p-3" required value={variant.productId} onChange={e=>setVariant({...variant,productId:e.target.value})}><option value="">Product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="rounded-xl border bg-white p-3" placeholder="SKU" required value={variant.sku} onChange={e=>setVariant({...variant,sku:e.target.value})}/><input className="rounded-xl border bg-white p-3" placeholder="Variant code" required value={variant.variantCode} onChange={e=>setVariant({...variant,variantCode:e.target.value})}/><input className="rounded-xl border bg-white p-3 md:col-span-2" placeholder="Color=Black,Size=M" required value={variant.attributesText} onChange={e=>setVariant({...variant,attributesText:e.target.value})}/><input className="rounded-xl border bg-white p-3" placeholder="Variant image URL" value={variant.imageUrl} onChange={e=>setVariant({...variant,imageUrl:e.target.value})}/><input type="number" step="0.01" min="0" className="rounded-xl border bg-white p-3" placeholder="Price" required value={variant.price} onChange={e=>setVariant({...variant,price:e.target.value})}/><input type="number" step="0.01" min="0" className="rounded-xl border bg-white p-3" placeholder="Sale price" value={variant.salePrice} onChange={e=>setVariant({...variant,salePrice:e.target.value})}/><input type="number" step="0.01" min="0" className="rounded-xl border bg-white p-3" placeholder="Cost price" value={variant.costPrice} onChange={e=>setVariant({...variant,costPrice:e.target.value})}/><input type="number" min="0" className="rounded-xl border bg-white p-3" placeholder="Opening stock" value={variant.openingStock} onChange={e=>setVariant({...variant,openingStock:e.target.value})}/></div><button className="mt-4 rounded-xl bg-[#1464f4] px-5 py-3 font-black text-white">Create variant</button></form>

    <section className="mt-6 space-y-4">{filtered.map(p=><div key={p.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase text-slate-400">{p.category?.name}{p.category?.nameBn?` / ${p.category.nameBn}`:''}{p.brand?.name?` · ${p.brand.name}`:''}</p><h3 className="mt-1 text-xl font-black">{p.name}{p.nameBn?` / ${p.nameBn}`:''}</h3><p className="mt-1 text-sm text-slate-500">{p.shortDescription}</p><p className="mt-2 text-xs font-bold text-blue-600">{Array.isArray(p.media)?p.media.length:0} media · {p.variants?.length||0} variants</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>beginEdit(p)} className="rounded-lg border px-3 py-2 text-xs font-bold">EDIT</button>{p.status!=='ACTIVE'?<button onClick={()=>activate(p.id,'ACTIVE')} className="rounded-lg bg-[#1464f4] px-3 py-2 text-xs font-bold text-white">ACTIVATE</button>:<button onClick={()=>activate(p.id,'INACTIVE')} className="rounded-lg border px-3 py-2 text-xs font-bold">DEACTIVATE</button>}</div></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{p.variants?.map((v:any)=><div key={v.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{v.sku}</p><p className="font-mono text-xs text-slate-500">{v.barcode}</p><p className="mt-1 text-xs">{Object.values(v.attributes||{}).join(' / ')}</p></div><div className="text-right"><p className="font-black">BDT {v.salePrice||v.price}</p><p className="text-xs text-slate-500">Available {v.stock}</p></div></div></div>)}</div></div>)}</section>
  </AdminShell>
}
