'use client';
import { FormEvent,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminShell from '@/components/admin-shell';
import { api } from '@/lib/api';
import { getStoredUser } from '@/lib/auth';
export default function DeliveryAdmin(){
 const r=useRouter();const [agents,setAgents]=useState<any[]>([]);const [orders,setOrders]=useState<any[]>([]);const [msg,setMsg]=useState('');const [f,setF]=useState({name:'',email:'',phone:'',password:'Delivery123!'});
 async function load(){const [a,o]=await Promise.all([api.get('/users/delivery-agents'),api.get('/admin/orders')]);setAgents(a.data);setOrders(o.data)}
 useEffect(()=>{const u=getStoredUser();if(!u||u.role!=='ADMIN'){r.replace('/login');return}load()},[r]);
 async function create(e:FormEvent){e.preventDefault();try{await api.post('/users/delivery-agents',f);setMsg('Delivery agent created.');setF({name:'',email:'',phone:'',password:'Delivery123!'});await load()}catch(e:any){setMsg(e?.response?.data?.message||'Could not create agent.')}}
 async function assign(orderId:string,deliveryAgentId:string){if(!deliveryAgentId)return;try{await api.patch(`/admin/orders/${orderId}/assign-delivery`,{deliveryAgentId});setMsg('Delivery agent assigned.');await load()}catch(e:any){setMsg(e?.response?.data?.message||'Could not assign agent.')}}
 return <AdminShell><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Fulfillment</p><h1 className="mt-2 text-4xl font-black">Delivery management</h1><p className="mt-2 text-slate-500">Create riders and assign packed orders for last-mile delivery.</p></div>{msg&&<p className="mt-5 rounded-2xl border bg-white p-4 text-sm font-semibold">{msg}</p>}<div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={create} className="h-fit rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Add delivery agent</h2><div className="mt-4 space-y-3">{[['name','Full name'],['email','Email'],['phone','Phone'],['password','Temporary password']].map(([k,l])=><label key={k} className="block text-sm font-bold">{l}<input type={k==='password'?'password':'text'} className="mt-2 w-full rounded-xl border p-3 font-normal" value={(f as any)[k]} required onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><button className="mt-5 w-full rounded-xl bg-slate-950 py-3 font-bold text-white">Create rider</button><div className="mt-6 border-t pt-5"><p className="text-sm font-bold">Active riders</p><div className="mt-3 space-y-2">{agents.map(a=><div key={a.id} className="rounded-xl bg-slate-50 p-3"><p className="font-bold">{a.name}</p><p className="text-xs text-slate-500">{a.phone} Â· {a.status}</p></div>)}</div></div></form><section className="space-y-4">{orders.filter(o=>!['DELIVERED','CANCELLED'].includes(o.status)).map(o=><div key={o.id} className="rounded-3xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-black">{o.orderNumber}</p><p className="mt-1 text-sm text-slate-500">{o.customerName} Â· {o.phone}</p><p className="mt-2 text-sm">{o.area?`${o.area}, `:''}{o.district||o.city}</p></div><div className="text-right"><p className="text-xl font-black">{o.status}</p>{o.trackingNumber&&<p className="text-xs text-slate-500">{o.trackingNumber}</p>}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><select className="rounded-xl border p-3" value={o.deliveryAgentId||''} onChange={e=>assign(o.id,e.target.value)}><option value="">Assign delivery agent...</option>{agents.filter(a=>a.status==='ACTIVE').map(a=><option key={a.id} value={a.id}>{a.name} Â· {a.phone}</option>)}</select>{o.deliveryAgent&&<span className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">Assigned: {o.deliveryAgent.name}</span>}</div></div>)}{!orders.length&&<div className="rounded-3xl border border-dashed p-12 text-center text-slate-500">No orders available.</div>}</section></div></AdminShell>
}

